Codigo/AjudAkiWeb/AjudAkiWeb/Models/AreaAtuacaoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AjudAkiWeb.Models
{
    public class AreaAtuacaoViewModel
    {
        [Display(Name ="Código")]
        [Required(ErrorMessage = "Código da área de atuação é obrigatório")]
        [Key]
        public uint Id { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        [StringLength(50)]
        public string Nome { get; set; } = null!;

        public ICollection<TipoServicoViewModel> TiposServico { get; set; } = new List<TipoServicoViewModel>();

    }
}

Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/AreaAtuacaoController.cs
using AutoMapper;
using AjudAkiWeb.Models;
using Core;
using Core.Service;
using Microsoft.AspNetCore.Mvc;

namespace AjudAkiWeb.Controllers
{
    public class AreaAtuacaoController : Controller
    {
        private readonly IAreaAtuacaoService _areaAtuacaoService;
        private readonly IAgendaService _agendaService;
        private readonly IMapper _mapper;

        public AreaAtuacaoController(IAreaAtuacaoService areaAtuacaoService, IAgendaService agendaService, IMapper mapper)
        {
            _areaAtuacaoService = areaAtuacaoService;
            _agendaService = agendaService;
            _mapper = mapper;
        }

        // GET: AreaAtuacaoController
        public ActionResult Index()
        {
            var listaAreasAtuacao = _areaAtuacaoService.GetAll();
            var listaAgendas = _agendaService.GetAll();

            ViewBag.ListaAgenda = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(listaAgendas.Select(a => new
            {
                Id = a.Id,
                Descricao = $"{a.Data:dd/MM/yyyy} - {a.Turno}"
            }), "Id", "Descricao");

            ViewBag.ListaAreasAtuacoes = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(listaAreasAtuacao, "Id", "Nome");

            var listaAreasAtuacaoViewModel = _mapper.Map<List<AreaAtuacaoViewModel>>(listaAreasAtuacao);
            return View(listaAreasAtuacaoViewModel);
        }

        // GET: AreaAtuacaoController/Details/5
        public ActionResult Details(uint id)
        {
            var areaAtuacao = _areaAtuacaoService.Get(id);
            var areaAtuacaoViewModel = _mapper.Map<AreaAtuacaoViewModel>(areaAtuacao);
            return View(areaAtuacaoViewModel);
        }

        // GET: AreaAtuacaoController/Create
        public ActionResult Create()
        {
            var areaAtuacaoViewModel = new AreaAtuacaoViewModel();
            return View(areaAtuacaoViewModel);
        }

        // POST: AreaAtuacaoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AreaAtuacaoViewModel areaAtuacaoViewModel)
        {
            if (ModelState.IsValid)
            {
                var areaAtuacao = _mapper.Map<Areaatuacao>(areaAtuacaoViewModel);
                _areaAtuacaoService.Create(areaAtuacao);
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: AreaAtuacaoController/Edit/5
        public ActionResult Edit(uint id)
        {
            var areaAtuacao = _areaAtuacaoService.Get(id);
            var areaAtuacaoViewModel = _mapper.Map<AreaAtuacaoViewModel>(areaAtuacao);
            return View(areaAtuacaoViewModel);
        }

        // POST: AreaAtuacaoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(uint id, AreaAtuacaoViewModel areaAtuacaoViewModel)
        {
            if (ModelState.IsValid)
            {
                var areaAtuacao = _mapper.Map<Areaatuacao>(areaAtuacaoViewModel);
                _areaAtuacaoService.Edit(areaAtuacao);
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: AreaAtuacaoController/Delete/5
        public ActionResult Delete(uint id)
        {
            var areaAtuacao = _areaAtuacaoService.Get(id);
            var areaAtuacaoViewModel = _mapper.Map<AreaAtuacaoViewModel>(areaAtuacao);
            return View(areaAtuacaoViewModel);
        }

        // POST: AreaAtuacaoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(uint id, AreaAtuacaoViewModel areaAtuacaoViewModel)
        {
            _areaAtuacaoService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/TipoServicoController.cs
using AjudAkiWeb.Models;
using AutoMapper;
using Core;
using Core.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AjudAkiWeb.Controllers
{
    public class TipoServicoController : Controller
    {
        private readonly IAreaAtuacaoService areaAtuacaoService;
        private readonly IAgendaService agendaService;
        private readonly ITipoServicoService tipoServicoService;
        private readonly IMapper mapper;

        public TipoServicoController(ITipoServicoService tipoServicoService, IAgendaService agendaService, IAreaAtuacaoService areaAtuacaoService, IMapper mapper)
        {
            this.tipoServicoService = tipoServicoService;
            this.agendaService = agendaService;
            this.areaAtuacaoService = areaAtuacaoService;
            this.mapper = mapper;
        }

        // GET: TipoServicoController
        // GET: TipoServicoController
        public ActionResult Index()
        {
            return RedirectToAction("Index", "AreaAtuacao");
        }

        // GET: TipoServicoController/Details/5
        public ActionResult Details(uint id)
        {
            var tipoServico = tipoServicoService.Get(id);
            if (tipoServico == null)
            {
                return NotFound();
            }
            var tipoServicoViewModel = mapper.Map<TipoServicoViewModel>(tipoServico);
            return View(tipoServicoViewModel);
        }

        // GET: TipoServicoController/Create
        public ActionResult Create()
        {
            var tipoServicoViewModel = new TipoServicoViewModel();
            PopulateLists(tipoServicoViewModel);
            return View(tipoServicoViewModel);
        }

        // POST: TipoServicoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TipoServicoViewModel tipoServicoViewModel)
        {
            if (ModelState.IsValid)
            {
                var tipoServico = mapper.Map<Tiposervico>(tipoServicoViewModel);
                tipoServicoService.Create(tipoServico);
                return RedirectToAction("Index", "AreaAtuacao");
            }
            PopulateLists(tipoServicoViewModel);
            return View(tipoServicoViewModel);
        }

        // GET: TipoServicoController/Edit/5
        public ActionResult Edit(uint id)
        {
            var tipoServico = tipoServicoService.Get(id);
            if (tipoServico == null)
            {
                return NotFound();
            }
            var tipoServicoViewModel = mapper.Map<TipoServicoViewModel>(tipoServico);
            PopulateLists(tipoServicoViewModel);
            return View(tipoServicoViewModel);
        }

        // POST: TipoServicoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(uint id, TipoServicoViewModel tipoServicoViewModel)
        {
            if (id != tipoServicoViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var tipoServico = mapper.Map<Tiposervico>(tipoServicoViewModel);
                tipoServicoService.Edit(tipoServico);
                return RedirectToAction("Index", "AreaAtuacao");
            }
            PopulateLists(tipoServicoViewModel);
            return View(tipoServicoViewModel);
        }

        // GET: TipoServicoController/Delete/5
        public ActionResult Delete(uint id)
        {
            var tipoServico = tipoServicoService.Get(id);
            if (tipoServico == null)
            {
                return NotFound();
            }
            var tipoServicoViewModel = mapper.Map<TipoServicoViewModel>(tipoServico);
            return View(tipoServicoViewModel);
        }

        // POST: TipoServicoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(uint id, TipoServicoViewModel collection)
        {
            try
            {
                tipoServicoService.Delete(id);
                return RedirectToAction("Index", "AreaAtuacao");
            }
            catch
            {
                return RedirectToAction("Index", "AreaAtuacao");
            }
        }

        private void PopulateLists(TipoServicoViewModel viewModel)
        {
            var listaAgenda = agendaService.GetAll();
            var listaAreasAtuacoes = areaAtuacaoService.GetAll();

            viewModel.ListaAgenda = new SelectList(listaAgenda.Select(a => new
            {
                Id = a.Id,
                Descricao = $"{a.Data:dd/MM/yyyy} - {a.Turno}"
            }), "Id", "Descricao", viewModel.IdAgenda);

            viewModel.ListaAreasAtuacoes = new SelectList(listaAreasAtuacoes, "Id", "Nome", viewModel.IdAreaAtuacao);
        }
    }
}

Codigo/AjudAkiWeb/AjudAkiWeb/Views/AreaAtuacao/Create.cshtml
@model AjudAkiWeb.Models.AreaAtuacaoViewModel

@{
    ViewData["Title"] = "Criar";
}

<h1>Criar Nova Área de Atuação</h1>

<h4>Preencha os dados abaixo:</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para a lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Codigo/AjudAkiWeb/AjudAkiWeb/Views/AreaAtuacao/Delete.cshtml
@model AjudAkiWeb.Models.AreaAtuacaoViewModel

@{
    ViewData["Title"] = "Apagar";
}

<h1>Apagar</h1>

<h3>Você tem certeza que quer apagar isso?</h3>
<div>
    <h4>Área de Atuação</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Apagar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar para a lista</a>
    </form>
</div>

Codigo/AjudAkiWeb/AjudAkiWeb/Views/AreaAtuacao/Details.cshtml
@model AjudAkiWeb.Models.AreaAtuacaoViewModel

@{
    ViewData["Title"] = "Detalhes";
}

<h1>Detalhes</h1>

<div>
    <h4>Área de Atuação</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-warning">Editar</a> |
    <a asp-action="Index">Voltar para a lista</a>
</div>

Codigo/AjudAkiWeb/AjudAkiWeb/Views/AreaAtuacao/Edit.cshtml
@model AjudAkiWeb.Models.AreaAtuacaoViewModel

@{
    ViewData["Title"] = "Editar Área de Atuação";
}


<link href="~/css/AreaAtuacao.css" rel="stylesheet" />


<div class="row mt-4">
    <!-- Sidebar -->
    <div class="col-md-3 mb-3">
        <div>
            <a href="#" class="admin-menu-item">
                <i class="fa-solid fa-calendar-days me-2"></i> Solicitações de serviços
            </a>
            <a href="#" class="admin-menu-item">
                <i class="fa-solid fa-cart-shopping me-2"></i> Minhas contratações
            </a>
            <a href="#" class="admin-menu-item">
                <i class="fa-solid fa-briefcase me-2"></i> Meus serviços
            </a>
            <a href="#" class="admin-menu-item">
                <i class="fa-solid fa-file-contract me-2"></i> Minha assinatura
            </a>
             <a href="#" class="admin-menu-item">
                <i class="fa-solid fa-pen me-2"></i> Editar dados
            </a>
            <a href="#" class="admin-menu-item active">
                <i class="fa-solid fa-gear me-2"></i> Administração
            </a>
             <a href="#" class="admin-menu-item">
                <i class="fa-solid fa-right-from-bracket me-2"></i> Sair
            </a>
        </div>
    </div>

    <!-- Main Content -->
    <div class="col-md-9">
        <div class="admin-header">
            <h2>Administração</h2>
            <p>Editar área de atuação.</p>
        </div>

        <div class="admin-card">
            
                <h4 class="text-primary fw-bold mb-4">Editar Área de Atuação</h4>
                
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
                    
                    <input type="hidden" asp-for="Id" />
                    
                    <div class="form-group mb-3">
                        <label asp-for="Nome" class="control-label fw-bold mb-1"></label>
                        <input asp-for="Nome" class="form-control" placeholder="Digite o nome da área" />
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>

                    <div class="d-flex gap-2">
                        <button type="submit" class="btn btn-success px-4">Salvar</button>
                        <a asp-action="Index" class="btn btn-secondary px-4">Voltar</a>
                    </div>
                </form>
            
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Codigo/AjudAkiWeb/AjudAkiWeb/Views/AreaAtuacao/Index.cshtml
@model IEnumerable<AjudAkiWeb.Models.AreaAtuacaoViewModel>

@{
    ViewData["Title"] = "Administração";
}

<link href="~/css/AreaAtuacao.css" rel="stylesheet" />

<div class="row mt-5">
    <!-- Sidebar (Keeping original structure as requested) -->
    <div class="col-md-3 mb-3">
        <div class="list-group">
            <a href="#" class="list-group-item admin-menu-item">
                <i class="fa-solid fa-calendar-days me-2"></i> Solicitações de serviços
            </a>
            <a href="#" class="list-group-item admin-menu-item">
                <i class="fa-solid fa-cart-shopping me-2"></i> Minhas contratações
            </a>
            <a href="#" class="list-group-item admin-menu-item">
                <i class="fa-solid fa-briefcase me-2"></i> Meus serviços
            </a>
            <a href="#" class="list-group-item admin-menu-item">
                <i class="fa-solid fa-file-contract me-2"></i> Minha assinatura
            </a>
             <a href="#" class="list-group-item admin-menu-item">
                <i class="fa-solid fa-pen me-2"></i> Editar dados
            </a>
            <a href="#" class="list-group-item admin-menu-item active">
                <i class="fa-solid fa-gear me-2"></i> Administração
            </a>
             <a href="#" class="list-group-item admin-menu-item">
                <i class="fa-solid fa-right-from-bracket me-2"></i> Sair
            </a>
        </div>
    </div>

    <!-- Main Content -->
    <div class="col-md-9">
        <div class="admin-header mb-3">
            <h2>Administração</h2>
            <p>Gerencie as áreas de atuação e serviços.</p>
        </div>

        <div class="admin-card">
            
            <!-- Adicionar Área de Atuação (Prototype Style) -->
            <div class="mb-5">
                <label class="admin-section-label">Adicione uma área de atuação</label>
                <form asp-action="Create" method="post" class="d-flex gap-3">
                     <input type="text" name="Nome" class="form-control" placeholder="Ex: encanador" required style="max-width: 400px;" />
                     <button type="submit" class="admin-btn-add">Adicionar</button>
                </form>
            </div>

            <!-- Adicionar Tipo de Serviço (Prototype Style) -->
            <div class="mb-5">
                <label class="admin-section-label">Adicione um tipo de serviço correspondente a uma área de atuação</label>
                <form asp-controller="TipoServico" asp-action="Create" method="post" class="d-flex align-items-center gap-2 flex-wrap">
                    <!-- Dropdown Area -->
                    <select name="IdAreaAtuacao" class="form-select" asp-items="ViewBag.ListaAreasAtuacoes" required style="max-width: 250px;">
                        <option value="">Selecione a área</option>
                    </select>
                    
                    <!-- Input Nome Serviço -->
                    <input type="text" name="Nome" class="form-control" placeholder="Ex: instalação de torneira" required style="max-width: 300px;" />

                    <!-- Hidden Agenda (Default selection logic needed or assumed first available) -->
                    <!-- Note: In prototype, Agenda isn't shown. We need it for the backend. 
                         I'll hide it or default it, but for now let's keep it visible but subtle or maybe just assume the user picks.
                         Actually, to match prototype, let's put it as a smaller select or handle it differently.
                         The user said "do not change context", so Agenda IS required.
                         I will make it a small select next to Area to not break the design too much.
                    -->
                    <select name="IdAgenda" class="form-select" asp-items="ViewBag.ListaAgenda" required style="max-width: 200px;">
                        <option value="">Agenda...</option>
                    </select>

                    <button type="submit" class="admin-btn-add">Adicionar</button>
                </form>
            </div>
        
            <!-- List Display (Accordion - To manage items) -->
            <h5 class="text-primary mb-3 mt-5 border-bottom pb-2">Áreas e Serviços Cadastrados</h5>

            <div class="accordion" id="accordionAreas">
            @foreach (var item in Model) {
                <div class="accordion-item mb-2 border rounded-3 overflow-hidden">
                    <h2 class="accordion-header" id="heading-@item.Id">
                        <button class="accordion-button collapsed fw-bold text-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-@item.Id" aria-expanded="false" aria-controls="collapse-@item.Id">
                            @Html.DisplayFor(modelItem => item.Nome)
                            <span class="badge bg-light text-dark ms-2 border">@item.TiposServico.Count serviços</span>
                        </button>
                    </h2>
                    <div id="collapse-@item.Id" class="accordion-collapse collapse" aria-labelledby="heading-@item.Id" data-bs-parent="#accordionAreas">
                        <div class="accordion-body bg-light">
                            <div class="d-flex justify-content-end mb-3">
                                <!-- Prototype has big red buttons. We'll simulate that style for the Area delete -->
                                <button class="admin-btn-delete" data-bs-toggle="modal" data-bs-target="#deleteModal" data-id="@item.Id" data-nome="@item.Nome" onclick="setDeleteModal(this)">
                                    Excluir área de atuação
                                </button>
                                <a asp-action="Edit" asp-route-id="@item.Id" class="admin-btn-edit ms-2">Editar</a>
                            </div>

                            <ul class="list-group">
                                @foreach (var servico in item.TiposServico)
                                {
                                    <li class="list-group-item d-flex justify-content-between align-items-center">
                                        <span>@servico.Nome</span>
                                        <div>
                                            <a asp-controller="TipoServico" asp-action="Edit" asp-route-id="@servico.Id" class="text-primary me-3"><i class="fa-solid fa-pen"></i></a>
                                        </div>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            }
            </div>

        </div>
    </div>
</div>

<!-- Modal Confirmar Exclusão -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Confirmar Exclusão</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Deseja realmente excluir a Área de Atuação <strong id="deleteItemName"></strong>?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
        <form asp-action="Delete" method="post">
            <input type="hidden" name="id" id="deleteItemId" />
            <button type="submit" class="btn btn-danger">Excluir</button>
        </form>
      </div>
    </div>
  </div>
</div>

<script>
    function setDeleteModal(element) {
        var id = element.getAttribute('data-id');
        var nome = element.getAttribute('data-nome');
        document.getElementById('deleteItemId').value = id;
        document.getElementById('deleteItemName').innerText = nome;
    }
</script>