Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/AgendaController.cs
using AjudAkiWeb.Models;
using AutoMapper;
using Core;
using Core.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AjudAkiWeb.Controllers
{
    public class AgendaController : Controller
    {
        private readonly IAgendaService agendaService;
        private readonly IMapper mapper;

        public AgendaController(IAgendaService agendaService, IMapper mapper)
        {
            this.agendaService = agendaService;
            this.mapper = mapper;
        }

        // GET: AgendaController
        public ActionResult Index()
        {
            var listaAgendas = agendaService.GetAll();
            var listaAgendasViewModel = mapper.Map<List<AgendaViewModel>>(listaAgendas);

            return View(listaAgendasViewModel);
        }

        // GET: AgendaController/Details/5
        public ActionResult Details(uint id)
        {
            var agenda = agendaService.Get(id);
            var agendaViewModel = mapper.Map<AgendaViewModel>(agenda);

            return View(agendaViewModel);
        }

        // GET: AgendaController/Create
        public ActionResult Create()
        {
            var agendaViewModel = new AgendaViewModel();

            var turnoListItems = Enum.GetValues(typeof(TurnoEnum))
                                   .Cast<TurnoEnum>()
                                   .Select(status => new SelectListItem
                                   {
                                       Value = status.ToString(),
                                       Text = status.ToString()
                                   }).ToList();

            agendaViewModel.TurnoList = new SelectList(turnoListItems, "Value", "Text");

            return View(agendaViewModel);
        }

        // POST: AgendaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AgendaViewModel agendaViewModel)
        {
            if (ModelState.IsValid)
            {
                var agenda = mapper.Map<Agendum>(agendaViewModel);
                agendaService.Create(agenda);
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: AgendaController/Edit/5
        public ActionResult Edit(uint id)
        {
            var agenda = agendaService.Get(id);
            var agendaViewModel = mapper.Map<AgendaViewModel>(agenda);

            var turnoListItems = Enum.GetValues(typeof(TurnoEnum))
                       .Cast<TurnoEnum>()
                       .Select(status => new SelectListItem
                       {
                           Value = status.ToString(),
                           Text = status.ToString()
                       }).ToList();

            agendaViewModel.TurnoList = new SelectList(turnoListItems, "Value", "Text");


            return View(agendaViewModel);
        }

        // POST: AgendaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(uint id, AgendaViewModel agendaViewModel)
        {
            if (ModelState.IsValid)
            {
                var agenda = mapper.Map<Agendum>(agendaViewModel);
                agendaService.Edit(agenda);
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: AgendaController/Delete/5
        public ActionResult Delete(uint id)
        {
            var agenda = agendaService.Get(id);
            var agendaViewModel = mapper.Map<AgendaViewModel>(agenda);

            return View(agendaViewModel);
        }

        // POST: AgendaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(AgendaViewModel agendaViewModel)
        {
            agendaService.Delete(agendaViewModel.Id);

            return RedirectToAction(nameof(Index));
        }
    }
}

Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/AvaliarController.cs
using AjudAkiWeb.Models;
using AutoMapper;
using Core;
using Core.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Service;

namespace AjudAkiWeb.Controllers
{
    public class AvaliarController : Controller
    {
        private readonly IContratacaoService contratacaoService;
        private readonly IAvaliarService avaliarService;
        private readonly IServicoService servicoService;
        private readonly IProfissionalService profissionalService;
        private readonly IMapper mapper;

        public AvaliarController(IAvaliarService avaliarService, IContratacaoService contratacaoService, IServicoService servicoService, IProfissionalService profissionalService, IMapper mapper)
        {
            this.avaliarService = avaliarService;
            this.contratacaoService = contratacaoService;
            this.servicoService = servicoService;
            this.profissionalService = profissionalService;
            this.mapper = mapper;
        }

        // GET: AvaliarController
        public ActionResult Index()
        {
            var listaAvaliar = avaliarService.GetAll();
            var listaAvaliarViewModel = mapper.Map<List<AvaliarViewModel>>(listaAvaliar);

            // Carregar nomes dos profissionais
            foreach (var avaliacao in listaAvaliarViewModel)
            {
                avaliacao.NomeProfissional = ObterNomeProfissional(avaliacao.IdContratacao);
            }

            return View(listaAvaliarViewModel);
        }
        // GET: AvaliarController/Details/5
        public ActionResult Details(uint id)
        {
            var avaliar = avaliarService.Get(id);
            var avaliarsViewModel = mapper.Map<AvaliarViewModel>(avaliar);

            // Carregar nome do profissional
            avaliarsViewModel.NomeProfissional = ObterNomeProfissional(avaliarsViewModel.IdContratacao);

            return View(avaliarsViewModel);
        }

        private string? ObterNomeProfissional(int idContratacao)
        {
            var contratacao = contratacaoService.Get((uint)idContratacao);
            if (contratacao != null)
            {
                var servico = servicoService.Get(contratacao.IdServico);
                if (servico != null)
                {
                    var profissional = profissionalService.Get(servico.IdProfissional);
                    return profissional?.Nome;
                }
            }
            return null;
        }

        // GET: AvaliarController/Create
        public ActionResult Create()
        {
            var avaliarViewModel = new AvaliarViewModel();
            // Materializar a lista primeiro para evitar erro de DataReader
            var listaContratacaos = contratacaoService.GetAll().ToList();
            
            // Criar SelectList com nome da contratação e profissional
            var items = new List<SelectListItem>();
            foreach (var contratacao in listaContratacaos)
            {
                var servico = servicoService.Get(contratacao.IdServico);
                string displayText = contratacao.Nome;
                
                if (servico != null)
                {
                    var profissional = profissionalService.Get(servico.IdProfissional);
                    if (profissional != null)
                    {
                        displayText = $"{contratacao.Nome} - Prof: {profissional.Nome}";
                    }
                }
                
                items.Add(new SelectListItem
                {
                    Value = contratacao.Id.ToString(),
                    Text = displayText
                });
            }
            
            avaliarViewModel.ListaContratacaos = new SelectList(items, "Value", "Text", null);
            return View(avaliarViewModel);
        }

        // POST: AvaliarController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AvaliarViewModel avaliarViewModel)
        {
            if (ModelState.IsValid)
            {
                var avaliar = mapper.Map<Avaliacao>(avaliarViewModel);
                avaliarService.Create(avaliar);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/ClienteController.cs
using AutoMapper;
using Core.Service;
using Microsoft.AspNetCore.Mvc;
using AjudAkiWeb.Models;
using Core;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AjudAkiWeb.Controllers
{
    public class ClienteController : Controller
    {
        private readonly IAssinaturaService assinaturaService;
        private readonly IClienteService clienteService;
        private readonly IMapper mapper;

        public ClienteController(IClienteService clienteService, IAssinaturaService assinaturaService, IMapper mapper)
        {
            this.clienteService = clienteService;
            this.assinaturaService = assinaturaService;
            this.mapper = mapper;
        }

        // GET: ClienteController
        public ActionResult Index()
        {
            var listaClientes = clienteService.GetAll();
            var listaClienteViewModel = mapper.Map<List<ClienteViewModel>>(listaClientes);

            return View(listaClienteViewModel);
        }

        // GET: ClienteController/Details/5
        public ActionResult Details(uint id)
        {
            var cliente = clienteService.Get(id);
            var clienteViewModel = mapper.Map<ClienteViewModel>(cliente);

            return View(clienteViewModel);
        }

        // GET: ClienteController/Create
        public ActionResult Create()
        {
            var clienteViewModel = new ClienteViewModel();
            clienteViewModel.DataNascimento = DateTime.Now;

            IEnumerable<Assinatura> listaAssinaturas = assinaturaService.GetAll();

            clienteViewModel.ListaAssinaturas = new SelectList(listaAssinaturas, "Id", "Nome", null);

            // Repreencher a lista de status
            var tipoPessoaListItems = Enum.GetValues(typeof(TipoPessoaEnum))
                .Cast<TipoPessoaEnum>()
                .Select(status => new SelectListItem
                {
                    Value = status.ToString(),
                    Text = status.ToString()
                })
                .ToList();

            clienteViewModel.TipoPessoaList = new SelectList(tipoPessoaListItems, "Value", "Text");


            return View(clienteViewModel);
        }

        // POST: ClienteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ClienteViewModel clienteViewModel)
        {
            if (ModelState.IsValid)
            {
                var cliente = mapper.Map<Pessoa>(clienteViewModel);
                clienteService.Create(cliente);
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: ClienteController/Edit/5
        public ActionResult Edit(uint id)
        {
            var cliente = clienteService.Get(id);
            var clienteViewModel = mapper.Map<ClienteViewModel>(cliente);

            IEnumerable<Assinatura> listaAssinaturas = assinaturaService.GetAll();

            clienteViewModel.ListaAssinaturas = new SelectList(listaAssinaturas, "Id", "Nome",
                        listaAssinaturas.FirstOrDefault(e => e.Id.Equals(cliente.IdAssinatura)));

            return View(clienteViewModel);
        }

        // POST: ClienteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(uint id, ClienteViewModel clienteViewModel)
        {
            if (ModelState.IsValid)
            {
                var cliente = mapper.Map<Pessoa>(clienteViewModel);
                clienteService.Edit(cliente);
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: ClienteController/Delete/5
        public ActionResult Delete(uint id)
        {
            var cliente = clienteService.Get(id);
            var clienteViewModel = mapper.Map<ClienteViewModel>(cliente);

            return View(clienteViewModel);
        }

        // POST: ClienteController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(ClienteViewModel clienteViewModel)
        {
            clienteService.Delete(clienteViewModel.Id);

            return RedirectToAction(nameof(Index));
        }
    }

}

Codigo/AjudAkiWeb/AjudAkiWeb/Controllers/ServicoController.cs
using AjudAkiWeb.Models;
using AutoMapper;
using Core;
using Core.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AjudAkiWeb.Controllers
{
    public class ServicoController : Controller
    {
        private readonly IProfissionalService profissionalService;
        private readonly IServicoService servicoService;
        private readonly ITipoServicoService tipoServicoService;
        private readonly IAreaAtuacaoService areaAtuacaoService;
        private readonly IMapper mapper;

        public ServicoController(IServicoService servicoService, IProfissionalService profissionalService, ITipoServicoService tipoServicoService, IAreaAtuacaoService areaAtuacaoService,IMapper mapper)
        {
            this.profissionalService = profissionalService;
            this.servicoService = servicoService;
            this.tipoServicoService = tipoServicoService;
            this.areaAtuacaoService = areaAtuacaoService;
            this.mapper = mapper;
        }

        // GET: ServicoController
        public ActionResult Index()
        {
            var listaServicos = servicoService.GetAll();
            var listaServicoViewModel = mapper.Map<List<ServicoViewModel>>(listaServicos);
            return View(listaServicoViewModel);
        }

        // GET: ServicoController/Details/5
        public ActionResult Details(uint id)
        {
            var servico = servicoService.Get(id);
            var servicoViewModel = mapper.Map<ServicoViewModel>(servico);
            return View(servicoViewModel);
        }

        // GET: ServicoController/Create
        public ActionResult Create()
        {
            var servicoViewModel = new ServicoViewModel();
            IEnumerable<Pessoa> listaProfissionais = profissionalService.GetAll();
            IEnumerable<Tiposervico> listaTiposServico = tipoServicoService.GetAll();
            IEnumerable<Areaatuacao> listaAreaAtuacao = areaAtuacaoService.GetAll();
            servicoViewModel.ListaTiposServico = new SelectList(listaTiposServico, "Id", "Nome", null);
            servicoViewModel.ListaProfissionais = new SelectList(listaProfissionais, "Id", "Nome", null);
            servicoViewModel.ListaAreaAtuacao = new SelectList(listaAreaAtuacao, "Id", "Nome", null);
            servicoViewModel.DataHoraSolicitacao = DateTime.Now;
            ViewBag.AreasAtuacao = areaAtuacaoService.GetAll();
            return View(servicoViewModel);
        }

        // POST: ServicoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ServicoViewModel servicoViewModel)
        {
            if (ModelState.IsValid)
            {
                var servico = mapper.Map<Servico>(servicoViewModel);
                servicoService.Create(servico);
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: ServicoController/Edit/5
        public ActionResult Edit(uint id)
        {
            var servico = servicoService.Get(id);
            var servicoViewModel = mapper.Map<ServicoViewModel>(servico);
            IEnumerable<Tiposervico> listaTiposServicos = tipoServicoService.GetAll();
            IEnumerable<Pessoa> listaProfissionais = profissionalService.GetAll();
            IEnumerable<Areaatuacao> listaAreaAtuacao = areaAtuacaoService.GetAll();

            servicoViewModel.ListaTiposServico = new SelectList(listaTiposServicos, "Id", "Nome",
                listaTiposServicos.FirstOrDefault(e => e.Id.Equals(servico.IdTipoServico)));

            servicoViewModel.ListaProfissionais = new SelectList(listaProfissionais, "Id", "Nome",
                listaProfissionais.FirstOrDefault(e => e.Id.Equals(servico.IdProfissional)));

            servicoViewModel.ListaAreaAtuacao = new SelectList(listaAreaAtuacao, "Id", "Nome",
                listaAreaAtuacao.FirstOrDefault(e => e.Id.Equals(servico.IdAreaAtuacao)));

            return View(servicoViewModel);
        }

        // POST: ServicoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(uint id, ServicoViewModel servicoViewModel)
        {
            if (ModelState.IsValid)
            {
                var servico = mapper.Map<Servico>(servicoViewModel);
                servicoService.Edit(servico);
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: ServicoController/Delete/5
        public ActionResult Delete(uint id)
        {
            var servico = servicoService.Get(id);
            var servicoViewModel = mapper.Map<ServicoViewModel>(servico);
            return View(servicoViewModel);
        }

        // POST: ProfissionalController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(uint id, ServicoViewModel servicoViewModel)
        {
            servicoService.Delete(servicoViewModel.Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Codigo/AjudAkiWeb/AjudAkiWeb/Views/Home/Index.cshtml
@{
    Layout = null;
    ViewData["Title"] = "Home Page";
}

<head>
    <link href="~/css/HomeIndex.css" rel="stylesheet" asp-append-version="true" />
</head>


<nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3 vw-100">
    <div class="container-fluid d-flex justify-content-between align-items-center">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
            <img src="~/img/Logo_AjudAki.webp" alt="AjudAkiWeb" style="height: 50px;" />
            <span class="text-primary ms-2">AjudAki</span>
        </a>
        <div class="navbar-collapse d-flex justify-content-center">
            <div class="d-flex flex-row flex-wrap justify-content-center">
                <a class="nav-link text-dark" asp-area="" asp-controller="Contratacao" asp-action="Index">Contratar Serviço</a>
                <a class="nav-link text-dark" asp-area="" asp-controller="Agenda" asp-action="Index">Agenda</a>
                <a class="nav-link text-dark" asp-area="" asp-controller="Avaliar" asp-action="Index">Avaliar</a>
                <a class="nav-link text-dark" asp-area="" asp-controller="AreaAtuacao" asp-action="Index">Area Atuação</a>
                <a class="nav-link text-dark" asp-area="" asp-controller="Assinatura" asp-action="Index">Assinatura</a>
                <a class="nav-link text-dark" asp-area="" asp-controller="PagarAssinatura" asp-action="Index">Pagar Assinatura</a>
                <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Cliente</a>
                <a class="nav-link text-dark" asp-area="" asp-controller="Profissional" asp-action="Index">Profissional</a>
                <a class="nav-link text-dark" asp-area="" asp-controller="SolicitacaoServico" asp-action="Index">Solicitação de Serviço</a>
                <a class="nav-link text-dark" asp-area="" asp-controller="Tiposervico" asp-action="Index">Tipo Serviço</a>
            </div>
        </div>
        <div class="forms flex-grow-1 d-flex">
            <a asp-area="" asp-controller="Servico" asp-action="Index" class="btn btn-servico" type="button">
                Ofertar Serviço <i class="fa-regular fa-money-bill-1 ms-2"></i>
            </a>

            <a asp-area="Identity" asp-page="/Account/Manage/Index" class="btn btn-conta" type="button">
                Minha Conta <i class="fa fa-user ms-2"></i>
            </a>
        </div>
    </div>
</nav>


<body>
    <section class="text-center">
        <div class="image-background">
            <h2 class="display-4">Agende agora a sua solução</h2>
            <h4> Sua solução em alguns cliques de distância</h4>

            <section class="search">
                <form action="/search" method="get">
                    <input type="search" name="query" placeholder="Área de atuação">
                    <select name="queryRegiao" required>
                        <option value="" disabled selected>Selecione um estado</option>
                        <option value="AC">Acre</option>
                        <option value="AL">Alagoas</option>
                        <option value="AP">Amapá</option>
                        <option value="AM">Amazonas</option>
                        <option value="BA">Bahia</option>
                        <option value="CE">Ceará</option>
                        <option value="DF">Distrito Federal</option>
                        <option value="ES">Espírito Santo</option>
                        <option value="GO">Goiás</option>
                        <option value="MA">Maranhão</option>
                        <option value="MT">Mato Grosso</option>
                        <option value="MS">Mato Grosso do Sul</option>
                        <option value="MG">Minas Gerais</option>
                        <option value="PA">Pará</option>
                        <option value="PB">Paraíba</option>
                        <option value="PR">Paraná</option>
                        <option value="PE">Pernambuco</option>
                        <option value="PI">Piauí</option>
                        <option value="RJ">Rio de Janeiro</option>
                        <option value="RN">Rio Grande do Norte</option>
                        <option value="RS">Rio Grande do Sul</option>
                        <option value="RO">Rondônia</option>
                        <option value="RR">Roraima</option>
                        <option value="SC">Santa Catarina</option>
                        <option value="SP">São Paulo</option>
                        <option value="SE">Sergipe</option>
                        <option value="TO">Tocantins</option>
                    </select>
                    <button class="botao" type="submit">Pesquisar</button>
                </form>
            </section>
        </div>
    </section>
<section class="categorias">
    <h4>Áreas de atuação</h4>
    <article>
        <img src="~/img/Reparos.png" alt="Reparos" class="categoria-icon">
        <p>Reparos</p>
    </article>
    <article>
        <img src="~/img/Diarista.png" alt="Diarista" class="categoria-icon">
        <p>Diarista</p>
    </article>
    <article>
        <img src="~/img/Encanador.png" alt="Encanador" class="categoria-icon">
        <p>Encanador</p>
    </article>
    <article>
        <img src="~/img/Eletricista.png" alt="Eletricista" class="categoria-icon">
        <p>Eletricista</p>
    </article>
    <article>
        <img src="~/img/Refrigerista.png" alt="Refrigerista" class="categoria-icon">
        <p>Refrigerista</p>
    </article>
    <article>
        <img src="~/img/Jardineiro.png" alt="Jardineiro" class="categoria-icon">
        <p>Jardineiro</p>
    </article>
    <article>
        <img src="~/img/Lavagem.png" alt="Lavagem forte" class="categoria-icon">
        <p>Lavagem forte</p>
    </article>
</section>
</body>